Repository Automattic/maintenance-mode-wp, pull requests merged in 2024-11, with the labels that each got.

#53 Composer: Add allow-plugins config
  composer.json
Labels: Type: maintenance

#54 CI: Refresh CI configs and Composer dependencies
  .github/workflows/cs-lint.yml
  .github/workflows/integrations.yml
  composer.json
  tests/maintenance-mode-testcase.php
Labels: Type: maintenance

#55 CS: Fix coding standards violations issues
  .github/workflows/cs-lint.yml
  .phpcs.xml.dist
  maintenance-mode.php
  template-maintenance-mode.php
  tests/bootstrap.php
  tests/maintenance-mode-testcase.php
  vipgo-helper.php
Labels: Type: maintenance

#56 Docs: Add new default theme screenshots
  .wordpress-org/screenshot-1.png
  .wordpress-org/screenshot-2.png
  .wordpress-org/screenshot-3.png
  .wordpress-org/screenshot-4.png
  .wordpress-org/screenshot-5.png
  .wordpress-org/screenshot-6.png
  .wordpress-org/screenshot-7.png
  .wordpress-org/screenshot-8.png
  readme.md
Labels: Type: maintenance, Type: documentation

#57 Docs: Add changelog file
  CHANGELOG.md
  readme.md
  readme.txt
Labels: Type: documentation

#58 Add Rector
  maintenance-mode.php
  rector.php
  template-maintenance-mode.php
  tests/bootstrap.php
  vipgo-helper.php
Labels: Type: maintenance

#50 Add UptimeRobot to ignore list
  vipgo-helper.php
Labels: enhancement

#59 CS: Address low severity violations
  .phpcs.xml.dist
  maintenance-mode.php
  tests/bootstrap.php
  tests/maintenance-mode-testcase.php
  vipgo-helper.php
Labels: Type: maintenance

#60 Template: improve template loading
  maintenance-mode.php
  readme.md
Labels: enhancement

#61 Docs: Consolidate two readme files
  README.md
  readme.txt
Labels: Type: documentation

#62 Add version bump script
  package-lock.json
  package.json
Labels: Type: maintenance

#63 Dev: Add/update development files
  .distignore
  .gitattributes
  .gitignore
  phpunit.xml.dist
Labels: Type: maintenance

#64 Release 0.3.0
  CHANGELOG.md
  README.md
  maintenance-mode.php
  package-lock.json
  package.json
Labels: Type: maintenance
